spring:
  application:
    name: example-cqrs
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Cache configuration
cache:
  type: redis